In [50]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# pip install wordcloud
from wordcloud import WordCloud
import math

In [94]:
# Load data and preview 

file = "../raw_data/players_15.csv"
df_15 = pd.read_csv(file, low_memory=False)

file = "../raw_data/players_16.csv"
df_16 = pd.read_csv(file, low_memory=False)

file = "../raw_data/players_17.csv"
df_17 = pd.read_csv(file, low_memory=False)

file = "../raw_data/players_18.csv"
df_18 = pd.read_csv(file, low_memory=False)

file = "../raw_data/players_19.csv"
df_19 = pd.read_csv(file, low_memory=False)

file = "../raw_data/players_20.csv"
df_20 = pd.read_csv(file, low_memory=False)

file = "../raw_data/players_21.csv"
df_21 = pd.read_csv(file, low_memory=False)

file = "../raw_data/players_22.csv"
df_22 = pd.read_csv(file, low_memory=False)

dfs = [df_15, df_16, df_17, df_18, df_19, df_20, df_21]
# dfs = [df_18, df_19, df_20, df_21]

year = 15
columns=['long_name', 'club_logo_url','nation_flag_url','club_flag_url','nation_logo_url','player_face_url','dob','player_url', 'real_face','nation_jersey_number','nation_position']
df_22.drop(columns=columns, inplace=True)

df_22 = df_22.add_suffix('_22')

for frame in dfs:
    frame.drop(columns=columns, inplace=True)
    df_22 = df_22.join(frame, rsuffix=f"_{year}")
    year += 1

df_22


# year = 18
# df_22 = df_22.add_suffix('_22')
# df_22 = df_22[['sofifa_id_22', 'overall_22', 'potential_22', 'value_eur_22']]

# for frame in dfs:
#     df_22[f'overall_{year}'] = df_22['sofifa_id_22'].map(frame.set_index('sofifa_id')['overall'])
#     df_22[f'potential_{year}'] = df_22['sofifa_id_22'].map(frame.set_index('sofifa_id')['potential'])
#     year += 1

# df_22

,sofifa_id_22,short_name_22,player_positions_22,overall_22,potential_22,value_eur_22,wage_eur_22,age_22,height_cm_22,weight_kg_22,...,ldm_21,cdm_21,rdm_21,rwb_21,lb_21,lcb_21,cb_21,rcb_21,rb_21,gk_21
0,158023,L. Messi,"RW, ST, CF",93,93,78000000.0,320000.0,34,170,72,...,65+3,65+3,65+3,66+3,62+3,52+3,52+3,52+3,62+3,19+3
1,188545,R. Lewandowski,ST,92,92,119500000.0,270000.0,32,185,81,...,61+3,61+3,61+3,65+3,61+3,54+3,54+3,54+3,61+3,20+3
2,20801,Cristiano Ronaldo,"ST, LW",91,91,45000000.0,270000.0,36,187,83,...,65+3,65+3,65+3,64+3,61+3,60+3,60+3,60+3,61+3,19+3
3,190871,Neymar Jr,"LW, CAM",91,91,129000000.0,270000.0,29,175,68,...,62+3,62+3,62+3,67+3,62+3,49+3,49+3,49+3,62+3,20+3
4,192985,K. De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,181,70,...,80+3,80+3,80+3,79+3,75+3,69+3,69+3,69+3,75+3,21+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19234,261962,Song Defu,CDM,47,52,70000.0,1000.0,22,180,64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19235,262040,C. Porter,CM,47,59,110000.0,500.0,19,175,70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19236,262760,N. Logue,CM,47,55,100000.0,500.0,21,178,72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19237,262820,L. Rudden,ST,47,60,110000.0,500.0,19,173,66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19238,264540,E. Lalchhanchhuaha,CAM,47,60,110000.0,500.0,19,167,61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
# # df = pd.DataFrame(data=df_22.drop(columns=['short_name', 'player_positions', 'club_name' 'overall', 'potential', 'long_name', 'club_logo_url','nation_flag_url','club_flag_url','nation_logo_url','player_face_url','dob','player_url',
# #            'real_face','nation_jersey_number','nation_position']))
# df = pd.DataFrame
# df['overall_15'] = df_22['sofifa_id'].map(df_15.set_index('sofifa_id')['overall'])
# df['overall_16'] = df_22['sofifa_id'].map(df_16.set_index('sofifa_id')['overall'])
# df['overall_17'] = df_22['sofifa_id'].map(df_17.set_index('sofifa_id')['overall'])
# df['overall_18'] = df_22['sofifa_id'].map(df_18.set_index('sofifa_id')['overall'])
# df['overall_19'] = df_22['sofifa_id'].map(df_19.set_index('sofifa_id')['overall'])
# df['overall_20'] = df_22['sofifa_id'].map(df_20.set_index('sofifa_id')['overall'])
# df['overall_21'] = df_22['sofifa_id'].map(df_21.set_index('sofifa_id')['overall'])
# df['overall_22'] = df_22['sofifa_id'].map(df_22.set_index('sofifa_id')['overall'])
# df['potential_15'] = df_22['sofifa_id'].map(df_15.set_index('sofifa_id')['potential'])
# df['potential_16'] = df_22['sofifa_id'].map(df_16.set_index('sofifa_id')['potential'])
# df['potential_17'] = df_22['sofifa_id'].map(df_17.set_index('sofifa_id')['potential'])
# df['potential_18'] = df_22['sofifa_id'].map(df_18.set_index('sofifa_id')['potential'])
# df['potential_19'] = df_22['sofifa_id'].map(df_19.set_index('sofifa_id')['potential'])
# df['potential_20'] = df_22['sofifa_id'].map(df_20.set_index('sofifa_id')['potential'])
# df['potential_21'] = df_22['sofifa_id'].map(df_21.set_index('sofifa_id')['potential'])
# df['potential_22'] = df_22['sofifa_id'].map(df_22.set_index('sofifa_id')['potential'])
# df.head()

In [82]:
# df_22['overall_21']

In [95]:
# data.RoofSurface.isnull().sum()
df_22.isnull().sum()
# data.RoofSurface.replace(np.nan, data.RoofSurface.mean(), inplace=True)
# data.RoofSurface.isnull().sum()b

sofifa_id_22             0
short_name_22            0
player_positions_22      0
overall_22               0
potential_22             0
                      ...
lcb_21                 295
cb_21                  295
rcb_21                 295
rb_21                  295
gk_21                  295
Length: 792, dtype: int64

In [96]:
# df_22 = df_22.dropna(subset=['value_eur_22', 'overall_15', 'potential_15', 'overall_16', 'potential_16', 'overall_17', 'potential_17', 'overall_18', 'potential_18', 'overall_19', 'potential_19', 'overall_20', 'potential_20', 'overall_21', 'potential_21'])
# df_22 = df_22.dropna(subset=['value_eur_22', 'overall_18', 'potential_18', 'overall_19', 'potential_19', 'overall_20', 'potential_20', 'overall_21', 'potential_21'])
# df_22.isnull().sum()

In [97]:
# print(df_22.shape)
# df_22.head()

In [53]:
# overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,league_level,international_reputation,work_rate,release_clause_eur,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed

In [54]:
# "overall","potential","value_eur","wage_eur","age","height_cm","weight_kg","league_level","international_reputation","work_rate","release_clause_eur","pace","shooting","passing","dribbling","defending","physic","attacking_crossing","attacking_finishing","attacking_heading_accuracy","attacking_short_passing","attacking_volleys","skill_dribbling","skill_curve","skill_fk_accuracy","skill_long_passing","skill_ball_control","movement_acceleration","movement_sprint_speed","movement_agility","movement_reactions","movement_balance","power_shot_power","power_jumping","power_stamina","power_strength","power_long_shots","mentality_aggression","mentality_interceptions","mentality_positioning","mentality_vision","mentality_penalties","mentality_composure","defending_marking_awareness","defending_standing_tackle","defending_sliding_tackle","goalkeeping_diving","goalkeeping_handling","goalkeeping_kicking","goalkeeping_positioning","goalkeeping_reflexes","goalkeeping_speed"

In [98]:
df_22 = df_22.dropna(subset=['wage_eur_22', 'league_level_22', 'value_eur_22', 'release_clause_eur_22'])
X = df_22[["overall_22","potential_22","value_eur_22","wage_eur_22","age_22","height_cm_22","weight_kg_22","league_level_22","international_reputation_22","release_clause_eur_22","pace_22","shooting_22","passing_22","dribbling_22","defending_22","physic_22","attacking_crossing_22","attacking_finishing_22","attacking_heading_accuracy_22","attacking_short_passing_22","attacking_volleys_22","skill_dribbling_22","skill_curve_22","skill_fk_accuracy_22","skill_long_passing_22","skill_ball_control_22","movement_acceleration_22","movement_sprint_speed_22","movement_agility_22","movement_reactions_22","movement_balance_22","power_shot_power_22","power_jumping_22","power_stamina_22","power_strength_22","power_long_shots_22","mentality_aggression_22","mentality_interceptions_22","mentality_positioning_22","mentality_vision_22","mentality_penalties_22","mentality_composure_22","defending_marking_awareness_22","defending_standing_tackle_22","defending_sliding_tackle_22","goalkeeping_diving_22","goalkeeping_handling_22","goalkeeping_kicking_22","goalkeeping_positioning_22","goalkeeping_reflexes_22"]]

In [78]:
# # dropping ones that dont have these
# X.shooting_22.replace(np.nan, 30.0, inplace=True)
# X.passing_22.replace(np.nan, 30.0, inplace=True)
# X.dribbling_22.replace(np.nan, 30.0, inplace=True)
# X.defending_22.replace(np.nan, 30.0, inplace=True)
# X.pace_22.replace(np.nan, 30.0, inplace=True)
# X.physic_22.replace(np.nan, 30.0, inplace=True)

# # physic_22                         0.110817
# # pace_22                           0.110817
# # defending_22                      0.110817
# # dribbling_22                      0.110817
# # passing_22                        0.110817
# # shooting_22 
# X.isnull().sum().sort_values(ascending=False)/len(X)

In [99]:
# Import the model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate


# Instanciate the model
model = LinearRegression()

# X = df_22
# Define X and y
X = X.drop(columns=['value_eur_22'])
# numerical_df = df_22.select_dtypes(include='number')
# X = numerical_df
y = df_22['value_eur_22']

print(y.head())
# Train the model on the data
# model.fit(X, y)
               
cv_results = cross_validate(model, X, y, cv=5)
print(cv_results['test_score'])
# cv_results
mean_score = cv_results['test_score'].mean()
mean_score

0     78000000.0
1    119500000.0
2     45000000.0
3    129000000.0
4    125500000.0
Name: value_eur_22, dtype: float64
[nan nan nan nan nan]

/Users/dougberks/.pyenv/versions/3.8.12/envs/opti_recruit/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning:
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/dougberks/.pyenv/versions/3.8.12/envs/opti_recruit/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/dougberks/.pyenv/versions/3.8.12/envs/opti_recruit/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 662, in fit
    X, y = self._validate_data(
  File "/Users/dougberks/.pyenv/versions/3.8.12/envs/opti_recruit/lib/python3.8/site-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/Users/dougberks/.pyenv/versions/3.8.12/envs/opti_recruit/lib/python3.8/site-packages/sklearn/utils/validation.py", line 964, in check_X_y
    X = check_array(
  File "/Users/dougberks/.pyenv/versions/3.8.12/envs/opti_recruit/lib/python3.8/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/Users/dougberks/.pyenv/versions/3.8.12/envs/opti_recruit/lib/python3.8/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(some_fits_failed_message, FitFailedWarning)

nan